#! /bin/sh
# /etc/init.d/radiopi

case "$1" in
  start)
    echo "Starting radiopi"
    cd /home/pi/radiopi
    sudo /usr/bin/python /home/pi/radiopi/radiopi.py &
  ;;
  stop)
    echo "Stopping lcdmenu"
    killall python
    ;;
  *)
    echo "Usage: /etc/init.d/radiopi {start|stop}"
    exit 1
    ;;
esac

exit 0
